s=input('Por favor digite qualquer coisa: ')
print('Isso é uma',type(s))
print('É um numêro?',s.isnumeric())
print('É alfabetico?',s.isalpha())
print('É alphanumerico?',s.isalnum())
print('Só tem espaço?',s.isspace())
print('Está EM MAIUSCULAS?',s.isupper())
print('Está em minusculas?',s.islower())
print('Está capitalizado?',s.istitle())
