frase=str(input('Digite uma frase: ')).strip().upper()
separa=frase.split()
print('Analisando a frase . . .')
print('Primeira palavra da frase: {}'.format(separa[0].capitalize()))
print('Última palavra da frase: {}'.format(separa[len(separa)-1].capitalize()))
print('A letra (a) aprece {} vezes'.format(frase.count('A')))
print('Primeira letra (a) aprece na posição {}'.format(frase.find('A')+1))
print('Última letra (a) aprece na posição {}'.format(frase.rfind('A')+1))
print('A letra (o) aprece {} vezes'.format(frase.count('O')))
print('Primeira letra (o) aprece na posição {}'.format(frase.find('O')+1))
print('Última letra (o) aprece na posição {}'.format(frase.rfind('O')+1))